name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - master

jobs:
  node-pkg-cd:
    name: Node package CD
    runs-on: ubuntu-latest
    steps:
      - uses: actalog/check-ci@main
      - uses: actions/checkout@v4
      - uses: actalog/node-pkg-cd@v1
        with:
          node-auth-token: ${{ secrets.NPM_TOKEN }}
