name: CI

on:
  - push

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:cov
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs:
      - tests
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
